name: quantum-crypto-trading
services:
- name: trading-app
  source_dir: /
  github:
    repo: shyamanurag/quantum
    branch: main
  run_command: gunicorn app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 2 --timeout 180
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 8000
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 15
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 5
  envs:
  - key: ENVIRONMENT
    value: production
  - key: DEPLOYMENT_MODE  
    value: production
  - key: TRADING_MODE
    value: paper
  - key: PAPER_TRADING
    value: "true"
  - key: ENABLE_AUTONOMOUS_TRADING
    value: "true"
  - key: BINANCE_TESTNET
    value: "true"
  - key: API_HOST
    value: "0.0.0.0"
  - key: DEBUG
    value: "false"
  - key: LOG_LEVEL
    value: INFO