# Optimized Scalping Configuration
# Quick in/quick out trading parameters

scalping:
  # Timing Controls (CRITICAL for scalping)
  signal_cooldown_seconds: 10        # 10 seconds between signals (vs 1 second default)
  symbol_cooldown_seconds: 30        # 30 seconds per symbol (vs 5 minutes)
  position_hold_max_minutes: 3       # Auto-exit after 3 minutes
  rapid_exit_minutes: 1              # Consider rapid exit after 1 minute
  
  # Risk Management (Tightened for scalping)
  stop_loss_ranges:
    tight: 0.15-0.5%                # Ultra-tight scalping
    normal: 0.3-0.8%               # Standard scalping
    loose: 0.5-1.5%                # Conservative scalping
  
  # Profit Targets (Risk:Reward optimized)
  risk_reward_ratios:
    aggressive: 1.2                 # 1.2:1 for high frequency
    balanced: 1.5                   # 1.5:1 for volume scalper
    conservative: 2.0               # 2.0:1 for momentum
  
  # Strategy-Specific Parameters
  strategies:
    volume_profile_scalper:
      signal_cooldown_seconds: 15
      stop_loss_range: 0.2-0.6%
      risk_reward_ratio: 1.5
      position_hold_max_minutes: 2
      
    news_impact_scalper:
      signal_cooldown_seconds: 10    # Fastest for news events
      stop_loss_range: 0.3-0.8%
      risk_reward_ratio: 1.8
      position_hold_max_minutes: 1   # Ultra-fast for news
      
    volatility_explosion:
      signal_cooldown_seconds: 20
      stop_loss_range: 0.4-1.0%
      risk_reward_ratio: 1.6
      position_hold_max_minutes: 3
      
    momentum_surfer:
      signal_cooldown_seconds: 25
      stop_loss_range: 0.3-0.7%
      risk_reward_ratio: 1.4
      position_hold_max_minutes: 2

# Trading Hours and Frequency
trading_hours:
  scalping_allowed: true
  max_trades_per_hour: 120          # 2 trades per minute max
  max_positions_concurrent: 5       # Max 5 positions at once
  
# Market Conditions
market_conditions:
  min_volume_for_scalping: 1000000  # Minimum volume for scalping
  avoid_low_liquidity: true
  pre_market_scalping: false        # Disable pre-market scalping
  
# Risk Controls
risk_controls:
  max_daily_scalping_loss: 10000    # ₹10,000 max daily loss
  max_position_size_scalping: 50000 # ₹50,000 max position
  auto_stop_on_3_losses: true       # Stop after 3 consecutive losses 